/**
 * Merges phase CSS files referenced by site-bundle.css into fewer physical bundles.
 * Run: npm run css:consolidate
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const appDir = join(__dirname, "..", "src", "app");
const stylesDir = join(appDir, "styles");
const bundlePath = join(stylesDir, "site-bundle.css");

const GROUPS = [
  {
    out: "consolidated-core.css",
    label: "Core premium UI",
    imports: [
      "../phase-g-premium.css",
      "../luxury-experience.css",
      "../phase2-ultra-premium.css",
      "../phase3-art-direction.css",
      "../phase6-scientific-credibility.css",
      "../phase6b-exhibit-cards.css",
    ],
  },
  {
    out: "consolidated-atmosphere.css",
    label: "Atmosphere & particles",
    imports: [
      "../phase4a-atmosphere.css",
      "../phase5-particle-system.css",
      "../phase5a-atmosphere-architecture.css",
      "../phase5b-atmosphere-bugfix.css",
      "../phase5c-atmosphere-balance.css",
      "../phase5d-continuous-atmosphere.css",
      "../phase6a-atmosphere-visibility.css",
      "../phase7-particle-reference-visibility.css",
    ],
  },
  {
    out: "consolidated-motion.css",
    label: "Scroll & motion",
    imports: ["../phase7-smooth-scroll.css"],
  },
];

function readCss(importPath) {
  const absolute = resolve(appDir, importPath.replace(/^\.\.\//, ""));
  if (!existsSync(absolute)) {
    throw new Error(`Missing CSS file: ${importPath} (${absolute})`);
  }
  return readFileSync(absolute, "utf8").trim();
}

function mergeGroup(group) {
  const sections = group.imports.map((importPath) => {
    const source = importPath.replace(/^\.\.\//, "");
    return `/* ── ${source} ── */\n${readCss(importPath)}`;
  });

  return [
    `/** ${group.label} — generated by scripts/consolidate-css.mjs */`,
    `/** Sources: ${group.imports.map((p) => p.replace(/^\.\.\//, "")).join(", ")} */`,
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");
}

let totalBytes = 0;

for (const group of GROUPS) {
  const merged = mergeGroup(group);
  const outPath = join(stylesDir, group.out);
  writeFileSync(outPath, merged, "utf8");
  totalBytes += Buffer.byteLength(merged, "utf8");
  console.log(`Wrote ${group.out} (${(Buffer.byteLength(merged, "utf8") / 1024).toFixed(1)} KB)`);
}

const newBundle = [
  "/**",
  " * Production stylesheet bundle — consolidated from phase CSS files.",
  " * Regenerate with: npm run css:consolidate",
  " */",
  "",
  '@import "./consolidated-core.css";',
  '@import "./consolidated-atmosphere.css";',
  '@import "./consolidated-motion.css";',
  "",
].join("\n");

writeFileSync(bundlePath, newBundle, "utf8");
console.log(`\nUpdated site-bundle.css (${GROUPS.length} bundles, ${(totalBytes / 1024).toFixed(1)} KB total source)`);
